### PR TITLE
Right clicking toolbar button will now open preferences (Issue #4)

### PR DESCRIPTION
**Pull request by trevermock54**
Issue #4 should now be fixed. Right clicking the Persona Switcher toolbar button will open the options menu.

### CODE REVIEW

**Comment by steppy08** [comment]
LGTM

**Comment by JasonGould81** [comment]
Looks good to me as well.

**Comment by kijames7** [comment]
Alright so in my VM the options work as intended, however there is a issue on my mac. It appears that the options menu does populate but the ok and cancel buttons do not show so I cannot make the options menu go away. I have tried tabbing and shift tabbing to see if I can navigate to the ok and cancel buttons but they are not there.

**Comment by kijames7** [comment]
Should be good to go Trevor, great job man.

**Pull request merged**
